### ISSUE TITLE
Небольшое ревью

### ISSUE THREAD

**Issue by yoshi-lyosha** [kiryanenko/BeFOUND#1]
Привет!
Нашёл немного времени чтобы посмотреть на ваш проект и сразу увидел кое-что.
Папки .idea, __pycache__, файлы .pyc, .log и прочий околомусор - это то, что должно быть только на ваших компьютерах. Нахождение подобного в репозитории - моветон. Я увидел, у вас недавно появился .gitignore, добавьте туда описанное, либо сгенерируйте стандартный под ваш стек.

И ещё, пустые папки - каркас будущих модулей вашего приложения или просто фича?

**Comment by hitryy** [comment]
@yoshi-lyosha привет! Околомусор уберем, всегда забивал и забывал об этом :) Спасибо за замечания - исправим.

Пустые папки для модулей, которые будут - они не просто так созданы )

**Comment by yoshi-lyosha** [comment]
Так и подумал.
Отпишитесь сюда, когда исправите - посмотрю более детально на проект, а то из-за обилия файлов я быстро сдался)

**Comment by yoshi-lyosha** [comment]
Кстати, раз этот вопрос открыт, позвольте спросить, а каким редактором вы сделали такие клёвые картинки, как, например, в ридми?
Я особо не заморачивался и делал в пэинте, но это как-то несерьёзно и недальновидно.

**Comment by hitryy** [comment]
@yoshi-lyosha делал на сайте [draw.io](www.draw.io).  Очень удобная вещь, в нее интегрирован гугл диск и другие облачные сервисы.

**Comment by FZambia** [comment]
Еще moqups.com оч крутой

**Comment by hitryy** [comment]
@FZambia спасибо за предложенный сервис. Посмотрел - вроде как круто выглядит, много всяких полезных элементов. Но бесплатная версия кажется какой-то очень обрезанной (

**Comment by hitryy** [comment]
@yoshi-lyosha почистил, обновил `.gitignore`, **задокументировал** самый важный код :)

**Comment by yoshi-lyosha** [comment]
Клёво, да, так гораздо лучше!
Но, правда, въехать в проект чтобы поревьювить я уже не успею, завтра защита, мы готовимся к ней.

**Comment by hitryy** [comment]
@yoshi-lyosha удачи с подготовкой!

**Comment by yoshi-lyosha** [comment]
@hitryy и вам! скоро уже встретимся
